spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/expense-tracker
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true

application:
  security:
    secret-key: 93f9941ffeb0acf0aee0ffb34e70a40d6ff54d450b34f82201fc85a4a4058c35
    expiration: 86_400_000
